spring:
   profiles: pro

---
oms:
  interface:
      getroomtype: http://oms.fanqiele.com/api/getRoomType
  img:
      host: http://img.fanqiele.com/

xz:
  user:
    code: XZ
    pwd: xz123456

pms:
  interface:
      innUrl: http://wwww.fanqiele.com/api/baseInfo/