spring:
   profiles: test
   data:
      jpa:
        repositories:
            enabled: true
   datasource:
          url: jdbc:postgresql://10.163.227.13:9999/tomato_staging
          username: ota
          password: ota@fanqie.COM888
          driver-class: org.postgresql.Driver
          max-active: 10
          min-idle: 1
          max-wait: 60000
          remove-abandoned: true
          test-on-borrow: true
          remove-abandoned-timeout: 120
          log-abandoned: true
          time-between-eviction-runs-millis: 60000
          validation-query: SELECT 1
   mvc:
     view:
       prefix: classpath:templates/
       suffix: .html
   jpa:
     show-sql: true

---
spring:
   profiles: dev
   data:
      jpa:
        repositories:
            enabled: true
   datasource:
          url: jdbc:postgresql://192.168.1.17:5432/xz_view
          username: ota
          password: ota
          driver-class: org.postgresql.Driver
   mvc:
     view:
       prefix: classpath:templates/
       suffix: .html
   jpa:
     show-sql: true

---
spring:
   profiles: pro

---
server:
    port: 80

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Map.xml,classpath:mybatis/mapper/*Mapper.xml

endpoints:
   shutdown:
      enabled: true

info:
  name: tomasky bill service
  description: tomasky bill service
  version: 1.0.0