server:
    port: 8181

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Map.xml,classpath:mybatis/mapper/*Mapper.xml

endpoints:
   shutdown:
      enabled: true

info:
  name: tomasky bill service
  description: tomasky bill service
  version: 1.0.0