spring:
   profiles: test
   data:
      jpa:
        repositories:
            enabled: true
   datasource:
          url: jdbc:postgresql://10.163.227.13:9999/tomato_staging
          username: ota
          password: ota@fanqie.COM888
          driver-class: org.postgresql.Driver
          max-active: 10
          min-idle: 1
          max-wait: 60000
          remove-abandoned: true
          test-on-borrow: true
          remove-abandoned-timeout: 120
          log-abandoned: true
          time-between-eviction-runs-millis: 60000
          validation-query: SELECT 1
   mvc:
     view:
       prefix: classpath:templates/
       suffix: .html
   jpa:
     show-sql: true

---
oms:
  interface:
      getroomtype: http://openapi.test.fanqielaile.com/api/getRoomType
  img:
      host: http://img.test.fanqiele.com

xz:
  user:
    code: XZ
    pwd: xz123456
  order:
      orderCallbackUrl: http://localhost:8081/product/orderCallbackUrl

pms:
   interface:
      innUrl: http://pms.test.fanqiele.com/api/baseInfo/